=== 940smiley/lmstudio-js/scaffolds/scaffold-json-schema-v1.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "required": ["scaffoldVersion", "name", "displayName", "description", "args"],
  "properties": {
    "scaffoldVersion": {
      "type": "number"
    },
    "name": {
      "type": "string"
    },
    "displayName": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "args": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["name", "default"],
        "properties": {
          "name": {
            "type": "string"
          },
          "replaceFrom": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "default": {
            "type": "string"
          },
          "isProjectName": {
            "type": "boolean"
          }
        }
      }
    }
  }
}

=== 940smiley/lmstudio-js/scaffolds/node-typescript/lms-scaffold.json
{
  "$schema": "./../scaffold-json-schema-v1.json",
  "scaffoldVersion": 1,
  "name": "node-typescript",
  "displayName": "Node.js with TypeScript",
  "description": "Empty Node.js TypeScript project with lmstudio.js",
  "args": [
    {
      "name": "Project Name",
      "default": "node-typescript",
      "replaceFrom": ["@lmstudio/scaffold-node-typescript"],
      "isProjectName": true
    }
  ]
}

=== 940smiley/lmstudio-js/scaffolds/node-typescript-empty/lms-scaffold.json
{
  "$schema": "./../scaffold-json-schema-v1.json",
  "scaffoldVersion": 1,
  "name": "node-typescript-empty",
  "displayName": "Node.js with TypeScript (Empty)",
  "description": "Completely empty minimalistic Node.js TypeScript project with lmstudio.js",
  "args": [
    {
      "name": "Project Name",
      "default": "node-typescript-empty",
      "replaceFrom": ["@lmstudio/scaffold-node-typescript-empty"],
      "isProjectName": true
    }
  ]
}
